name: nothotdog
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  provider: ^3.2.0
  font_awesome_flutter: ^8.5.0

  cupertino_icons: ^0.1.2
  image_picker: ^0.6.1+4
  camera:
  path_provider: ^1.3.0
  mlkit: ^0.14.1
  shimmer:
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  module:
    androidX: true
    androidPackage: com.bimsina
    iosBundleIdentifier: com.bimsina

  # assets:
  #  - assets/

  fonts:
    - family: Sans
      fonts:
        - asset: assets/SourceSansPro-Regular.ttf
        - asset: assets/SourceSansPro-Bold.ttf
          weight: 700
